### ISSUE TITLE
Editing a linked @import file from primary doesn't trickle to recompile

### ISSUE THREAD

**Issue by replete** [mockko/livereload#109]
Best explained with this .less snippet:

``` css
/* This file is app.less */

@import "reset.less";
@import "dependency.less";

html {
border:100px solid red}

@import "some-module.less"

```

Editing `some-module.less` (or any imported) triggers a refresh in the browser, but not a recompile of `app.less`.

Is there any way to force a recompile of everything? The only solution is to save `some-module.less` changes and then add a space to `app.less` - which isn't great.
